on: [push, pull_request]
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Test compile for Arduino
      uses: ArminJo/arduino-test-compile@v3
      with:
        arduino-board-fqbn: arduino:avr:mega # optional, default is arduino:avr:uno

